  File "bot.py", line 25
    async def on_message(message):
        ^
SyntaxError: invalid syntax
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 44, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 44, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 44, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 132, in on_message
    subreddit = reddit.subreddit(subreddit_name)  # makes subreddit
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/helpers.py", line 180, in __call__
    return Subreddit(self._reddit, display_name=display_name)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/subreddit.py", line 436, in __init__
    "Either `display_name` or `_data` must be provided."
TypeError: Either `display_name` or `_data` must be provided.
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 233, in on_message
    code) + '\n\nIf you are being spamed by codes, dm me here: https://bwac.pro/trb')
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/mixins/messageable.py", line 49, in message
    self._reddit.post(API_PATH["compose"], data=data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 525, in post
    return self._objector.objectify(data)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/objector.py", line 158, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: USER_DOESNT_EXIST: 'that user doesn't exist' on field 'to'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    for moderator in subreddit.moderator():
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/subreddit.py", line 2032, in __call__
    return self.subreddit._reddit.get(url, params=params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 442, in get
    data = self.request("GET", path, params=params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 577, in request
    method, path, data=data, files=files, params=params
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 185, in request
    params=params, url=url)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 130, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.Redirect: Redirect to /subreddits/search
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 67, in on_message
    for moderator in subreddit.moderator():
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/subreddit.py", line 2032, in __call__
    return self.subreddit._reddit.get(url, params=params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 442, in get
    data = self.request("GET", path, params=params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 577, in request
    method, path, data=data, files=files, params=params
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 185, in request
    params=params, url=url)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 130, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.Redirect: Redirect to /subreddits/search
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 44, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 44, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 44, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 49, in on_message
    await message.channel.send(message.author.mention + ' Check your dms ' + secure_random.choice(emojis))
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50013): Missing Permissions
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 44, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 791, in send
    channel = await self._get_channel()
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/user.py", line 659, in _get_channel
    ch = await self.create_dm()
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/user.py", line 682, in create_dm
    data = await state.http.start_private_message(self.id)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 222, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 BAD REQUEST (error code: 50033): Invalid Recipient(s)
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 44, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 44, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 44, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 44, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 44, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 44, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 44, in on_message
    await message.author.send(embed=help)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 168, in on_message
    user.add_field(name='Karma:', value=user_r.comment_karma, inline=False)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/base.py", line 30, in __getattr__
    self._fetch()
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/redditor.py", line 133, in _fetch
    data = self._fetch_data()
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/models/reddit/redditor.py", line 130, in _fetch_data
    return self._reddit.request("GET", path, params)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/praw/reddit.py", line 577, in request
    method, path, data=data, files=files, params=params
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 185, in request
    params=params, url=url)
  File "/home/bobwithacamera/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 130, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.NotFound: received 404 HTTP response
Ignoring exception in on_message
Traceback (most recent call last):
  File "bot.py", line 185, in on_message
    with open("users/" + user_id + '.json') as user_data:
